import type { Product } from './types';

export const pizzas: Product[] = [
  {
    id: 1,
    title: 'Итальянская',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'hot',
    image: '/images/italy.png',
  },
  {
    id: 2,
    title: 'Маргарита',
    subtitle: 'Тесто со шпинатом, молодой сыр и колбаски, много колбасок',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'hot',
    image: '/images/margarita.png',
  },
  {
    id: 3,
    title: 'Барбекю',
    subtitle: 'Цыплёнок (маленький кура), оливки, моцарелла, соус барбекю',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'hot',
    image: '/images/bbq.png',
  },
  {
    id: 4,
    title: 'Вегетарианская',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'vegan',
    image: '/images/vegan.png',
  },
  {
    id: 5,
    title: 'Мясная',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'meat',
    image: '/images/meat.png',
  },
  {
    id: 6,
    title: 'Овощная',
    subtitle: 'Тесто со шпинатом, молодой сыр и колбаски, много колбасок',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'vegan',
    image: '/images/vegetable.png',
  },
  {
    id: 7,
    title: 'Римская',
    subtitle: 'Цыплёнок (маленький кура), оливки, моцарелла, соус барбекю',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'meat',
    image: '/images/rome.png',
  },
  {
    id: 8,
    title: 'С грибами',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'vegan',
    image: '/images/mashroom.png',
  },
  {
    id: 9,
    title: 'Сырная',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'cheese',
    image: '/images/cheese.png',
  },
  {
    id: 10,
    title: 'Четыре сыра',
    subtitle: 'Тесто со шпинатом, молодой сыр и колбаски, много колбасок',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'cheese',
    image: '/images/four_cheese.png',
  },
  {
    id: 11,
    title: 'Пепперони Фреш с томатами',
    subtitle: 'Циплёнок (маленький кура), оливки, моцарелла, соус барбекю',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'meat',
    image: '/images/pepperoni.png',
  },
  {
    id: 12,
    title: 'Ветчина и сыр',
    subtitle: 'Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик',
    size: ['20', '30', '40'],
    price: [479, 679, 879],
    type: 'cheese',
    image: '/images/ham_cheese.png',
  },
];
